#!/bin/sh

alias ^L="clear;"
alias gf="git fetch"
alias gp="git push"
alias ll="clear;ls -alh;"
alias rc="RAILS_ENV=development foreman run bundle exec rails console"
alias reload="source ~/.bashrc"
alias yolo="sudo"
alias gti="git"
