#!/bin/sh

export PATH=$HOME/.npm/bin:$PATH
export PATH=/bin:$PATH
export PATH=/opt/X11/bin:$PATH
export PATH=/sbin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/git/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/sbin:$PATH
export PATH=$PATH:$GOPATH/bin
export PATH="$(brew --prefix qt@5.5)/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
export PATH="$PATH:$HOME/.rvm/bin"

export GOPATH=$HOME/go
