#!/bin/sh

export PATH=$HOME/npm/bin:$PATH
export PATH=/bin:$PATH
export PATH=/opt/X11/bin:$PATH
export PATH=/sbin:$PATH
export PATH=/Users/josh/.rvm/bin:$PATH
export PATH=/Users/josh/.rvm/gems/ruby-2.1.3/bin:$PATH
export PATH=/Users/josh/.rvm/gems/ruby-2.1.3@global/bin:$PATH
export PATH=/Users/josh/.rvm/rubies/ruby-2.1.3/bin:$PATH
export PATH=/Users/josh/npm/bin:$PATH
export PATH=/usr/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/git/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/sbin:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
